# PKGBUILD generated by pipman
# Python package author: Greg Lamp <greg@yhathq.com>
pkgname=python-pandasql
pkgver=0.7.3
pkgrel=1
pkgdesc="sqldf for pandas"
arch=(any)
url="https://github.com/yhat/pandasql/"
license=(Copyright (c) 2013 Yhat, Inc.)
makedepends=("python" "python-pip")
build() {
  pip install --no-deps --target="pandasql" pandasql
}
package() {
  mkdir -p $pkgdir/usr/lib/python3.6/site-packages/
  cp -r $srcdir/pandasql/* $pkgdir/usr/lib/python3.6/site-packages/
}